name: Build image

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build JWT
        run: docker build -t ghcr.io/kacperszurek/jwt:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry
        run: docker push ghcr.io/kacperszurek/jwt:latest
